name: build

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:

concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.sha || github.sha }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [arm64,x64,x86]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Hash
      run: dotnet publish src\Hash.Wpf -p:PublishProfile=win-${{ matrix.arch }}

    - name: Build MSI
      run: dotnet build src\WixInstallerSetup --arch ${{ matrix.arch }} --no-dependencies #--output src\WixInstallerSetup\bin\${{ matrix.arch }}\Release -p:Platform=${{ matrix.arch }}
      env:
        Configuration: Release
        Platform: ${{ matrix.arch }}
        OutputPath: bin\${{ matrix.arch }}\Release

    - run: tree /F

    - name: Copy build artifacts
      run: |
        mkdir artifact
        copy src\Hash.Wpf\publish\win-${{ matrix.arch }}\HashCalculator.exe artifact\
        copy src\WixInstallerSetup\bin\${{ matrix.arch }}\Release\ja-jp\HashCalculator-Setup.msi artifact\

    - run: tree /F

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win-${{ matrix.arch }}
        path: artifact\

  build-portable:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Hash
      run: dotnet build src\Hash.Wpf #-v diag -c Release -p:Platform="Any CPU" -o src\Hash.Wpf\bin\Release
      env:
        Configuration: Release
        Platform: Any CPU
        OutputPath: bin\Release

    - run: tree /F

    - name: Copy build artifacts
      run: |
        mkdir artifact
        xcopy src\Hash.Wpf\bin\Release\ artifact\ /e
        del artifact\*.pdb

    - run: tree /F

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win-anycpu-portable
        path: artifact\
