name: release

run-name: Release ${{ github.ref_name }}

on: workflow_dispatch

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  build:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: win-*

      - run: tree

      - name: Copy and Rename, Compress
        run: |
          Copy-Item -PassThru ./win-arm64/HashCalculator-Setup.msi HashCalculator-${{ github.ref_name }}-arm64-Setup.msi
          Copy-Item -PassThru ./win-x64/HashCalculator-Setup.msi HashCalculator-${{ github.ref_name }}-x64-Setup.msi
          Copy-Item -PassThru ./win-x86/HashCalculator-Setup.msi HashCalculator-${{ github.ref_name }}-x86-Setup.msi
          Compress-Archive -PassThru ./win-anycpu-portable/* HashCalculator-Portable-${{ github.ref_name }}-AnyCPU.zip

      - run: tree

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            HashCalculator-*-arm64-Setup.msi
            HashCalculator-*-x64-Setup.msi
            HashCalculator-*-x86-Setup.msi
            HashCalculator-Portable-*-AnyCPU.zip
          draft: true
