name: test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Test Hash
        run: |
          dotnet test ./tests/Hash.Core.Tests/ -- --coverage --coverage-output-format cobertura --coverage-output $GITHUB_WORKSPACE/coverage.cobertura.xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ${{ github.workspace }}/coverage.cobertura.xml
          fail_ci_if_error: true

      - name: Add Link to Step Summary
        run: |
          echo "### Codecov" >> $GITHUB_STEP_SUMMARY
          echo "https://codecov.io/gh/${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "##### Default Branch" >> $GITHUB_STEP_SUMMARY
          echo "![codecov](https://codecov.io/gh/${{ github.repository }}/graph/badge.svg?token=${{ vars.CODECOV_GRAPH_TOKEN }})" >> $GITHUB_STEP_SUMMARY
