name: test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Test Hash
        run: |
          dotnet test ./tests/Hash.Core.Tests/

      # # Retry integration tests if first attempt fails
      # - name: Run interaction tests
      #   uses: nick-fields/retry@v3
      #   with:
      #     timeout_minutes: 15
      #     max_attempts: 2
      #     shell: pwsh
      #     command: |
